In [107]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [108]:
user_movie = pd.DataFrame([\
                             ('Abelardo', 'Life of Pi'),
                             ('Abelardo', 'Donnie Darko'),
                             ('Abelardo', 'Titanic'),
                             ('Cris', 'Chuck'),
                             ('Cris', 'Apocalypse now'),
                             ('Obama', 'Bastardos Inglórios'),
                             ('Obama', 'Titanic'),
                             ('Obama', 'Brasileirinhas'),
                             ('ElTaradão', 'Francesinhas'),
                             ('ElTaradão', 'Espanholinhas')
                             ], columns=['user', 'movie'])

In [109]:
movie_tag_ = pd.DataFrame([\
                         ('Life of Pi', 'Fantasia'),
                         ('Life of Pi', 'Surto'),
                         ('Life of Pi', 'Oscar'),
                         ('Life of Pi', 'Drama'),
                         ('Life of Pi', 'Aventura'),
                         ('Donnie Darko', 'Surto'),
                         ('Donnie Darko', 'Drama'),
                         ('Donnie Darko', 'Meio maluco'),
                         ('Titanic', 'Drama'),
                         ('Titanic', 'Romance'),
                         ('Titanic', 'Leonardo DiCaprio'),
                         ('Chuck', 'Terror'),
                         ('Chuck', 'Comédia'),
                         ('Apocalypse now', 'Drama'),
                         ('Apocalypse now', 'Guerra'),
                         ('Bastardos Inglórios', 'Guerra'),
                         ('Bastardos Inglórios', 'Drama'),
                         ('Bastardos Inglórios', 'Aventura'),
                         ('Brasileirinhas', 'Pornô'),
                         ('Brasileirinhas', 'Nacional'),
                         ('Brasileirinhas', 'Milf'),
                         ('Francesinhas', 'Pornô'),
                         ('Francesinhas', 'Internacional'),
                         ('Espanholinhas', 'Pornô'),
                         ('Espanholinhas', 'Internacional'),
                         ('Espanholinhas', 'Milf')], columns=['movie', 'tag'])

# User x tag

In [110]:
user_tag = pd.merge(user_movie, movie_tag_).groupby(['user', 'tag']).count().unstack().fillna(0)
user_tag

             movie                                              \
tag       Aventura Comédia Drama Fantasia Guerra Internacional
user
Abelardo       1.0     0.0   3.0      1.0    0.0           0.0
Cris           0.0     1.0   1.0      0.0    1.0           0.0
ElTaradão      0.0     0.0   0.0      0.0    0.0           2.0
Obama          1.0     0.0   2.0      0.0    1.0           0.0

                                                                           \
tag       Leonardo DiCaprio Meio maluco Milf Nacional Oscar Pornô Romance
user
Abelardo                1.0         1.0  0.0      0.0   1.0   0.0     1.0
Cris                    0.0         0.0  0.0      0.0   0.0   0.0     0.0
ElTaradão               0.0         0.0  1.0      0.0   0.0   2.0     0.0
Obama                   1.0         0.0  1.0      1.0   0.0   1.0     1.0


tag       Surto Terror
user
Abelardo    2.0    0.0
Cris        0.0    1.0
ElTaradão   0.0    0.0
Obama       0.0    0.0

In [111]:
user_tag = user_tag.div(user_tag.sum(axis=1), axis=0)
user_tag

              movie                                                      \
tag        Aventura Comédia     Drama  Fantasia    Guerra Internacional
user
Abelardo   0.090909    0.00  0.272727  0.090909  0.000000           0.0
Cris       0.000000    0.25  0.250000  0.000000  0.250000           0.0
ElTaradão  0.000000    0.00  0.000000  0.000000  0.000000           0.4
Obama      0.111111    0.00  0.222222  0.000000  0.111111           0.0

                                                                       \
tag       Leonardo DiCaprio Meio maluco      Milf  Nacional     Oscar
user
Abelardo           0.090909    0.090909  0.000000  0.000000  0.090909
Cris               0.000000    0.000000  0.000000  0.000000  0.000000
ElTaradão          0.000000    0.000000  0.200000  0.000000  0.000000
Obama              0.111111    0.000000  0.111111  0.111111  0.000000


tag           Pornô   Romance     Surto Terror
user
Abelardo   0.000000  0.090909  0.181818   0.00
Cris       0.000000  0.000000  0.000000   0.25
ElTaradão  0.400000  0.000000  0.000000   0.00
Obama      0.111111  0.111111  0.000000   0.00

# Movie x tag

In [112]:
movie_tag = pd.get_dummies(movie_tag_, columns=['tag'], prefix='', prefix_sep='').groupby('movie').sum()
movie_tag

,Aventura,Comédia,Drama,Fantasia,Guerra,Internacional,Leonardo DiCaprio,Meio maluco,Milf,Nacional,Oscar,Pornô,Romance,Surto,Terror
movie,,,,,,,,,,,,,,,
Apocalypse now,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bastardos Inglórios,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Brasileirinhas,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
Chuck,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Donnie Darko,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Espanholinhas,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
Francesinhas,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Life of Pi,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
Titanic,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [113]:
movie_tag = movie_tag.div(movie_tag.sum(axis=1), axis=0)
movie_tag

,Aventura,Comédia,Drama,Fantasia,Guerra,Internacional,Leonardo DiCaprio,Meio maluco,Milf,Nacional,Oscar,Pornô,Romance,Surto,Terror
movie,,,,,,,,,,,,,,,
Apocalypse now,0.000000,0.0,0.500000,0.0,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
Bastardos Inglórios,0.333333,0.0,0.333333,0.0,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
Brasileirinhas,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.333333,0.333333,0.0,0.333333,0.000000,0.000000,0.0
Chuck,0.000000,0.5,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.5
Donnie Darko,0.000000,0.0,0.333333,0.0,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.0,0.000000,0.000000,0.333333,0.0
Espanholinhas,0.000000,0.0,0.000000,0.0,0.000000,0.333333,0.000000,0.000000,0.333333,0.000000,0.0,0.333333,0.000000,0.000000,0.0
Francesinhas,0.000000,0.0,0.000000,0.0,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000,0.0,0.500000,0.000000,0.000000,0.0
Life of Pi,0.200000,0.0,0.200000,0.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.2,0.000000,0.000000,0.200000,0.0
Titanic,0.000000,0.0,0.333333,0.0,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.0,0.000000,0.333333,0.000000,0.0

# User x Movie

In [114]:
um = np.dot(user_tag.values, movie_tag.values.T)
um

array([[ 0.13636364,  0.12121212,  0.        ,  0.        ,  0.18181818,
         0.        ,  0.        ,  0.14545455,  0.15151515],
       [ 0.25      ,  0.16666667,  0.        ,  0.25      ,  0.08333333,
         0.        ,  0.        ,  0.05      ,  0.08333333],
       [ 0.        ,  0.        ,  0.2       ,  0.        ,  0.        ,
         0.33333333,  0.4       ,  0.        ,  0.        ],
       [ 0.16666667,  0.14814815,  0.11111111,  0.        ,  0.07407407,
         0.07407407,  0.05555556,  0.06666667,  0.14814815]])

### removendo filmes já vistos

In [115]:
usu_ja_visto = pd.get_dummies(user_movie, columns=['movie'], prefix='', prefix_sep='').groupby('user').sum().applymap(lambda x: {0.: 1., 1.:0.}[x])

In [116]:
um = um * usu_ja_visto.values

In [117]:
um = pd.DataFrame(um, columns=movie_tag.T.columns, index=user_tag.index)

In [118]:
um

movie,Apocalypse now,Bastardos Inglórios,Brasileirinhas,Chuck,Donnie Darko,Espanholinhas,Francesinhas,Life of Pi,Titanic
user,,,,,,,,,
Abelardo,0.136364,0.121212,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
Cris,0.000000,0.166667,0.0,0.0,0.083333,0.000000,0.000000,0.050000,0.083333
ElTaradão,0.000000,0.000000,0.2,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
Obama,0.166667,0.000000,0.0,0.0,0.074074,0.074074,0.055556,0.066667,0.000000

In [122]:
um.loc['Obama'].sort_values(ascending=False)[:2]

movie
Apocalypse now    0.166667
Espanholinhas     0.074074
Name: Obama, dtype: float64

In [120]:
pd.merge(user_movie, pd.get_dummies(movie_tag_, columns=['tag'], prefix='', prefix_sep=''), left_on='movie', right_on='movie').groupby(['user', 'movie']).sum()

                               Aventura  Comédia  Drama  Fantasia  Guerra  \
user      movie
Abelardo  Donnie Darko              0.0      0.0    1.0       0.0     0.0
          Life of Pi                1.0      0.0    1.0       1.0     0.0
          Titanic                   0.0      0.0    1.0       0.0     0.0
Cris      Apocalypse now            0.0      0.0    1.0       0.0     1.0
          Chuck                     0.0      1.0    0.0       0.0     0.0
ElTaradão Espanholinhas             0.0      0.0    0.0       0.0     0.0
          Francesinhas              0.0      0.0    0.0       0.0     0.0
Obama     Bastardos Inglórios       1.0      0.0    1.0       0.0     1.0
          Brasileirinhas            0.0      0.0    0.0       0.0     0.0
          Titanic                   0.0      0.0    1.0       0.0     0.0

                               Internacional  Leonardo DiCaprio  Meio maluco  \
user      movie
Abelardo  Donnie Darko                   0.0                0.0          1.0
          Life of Pi                     0.0                0.0          0.0
          Titanic                        0.0                1.0          0.0
Cris      Apocalypse now                 0.0                0.0          0.0
          Chuck                          0.0                0.0          0.0
ElTaradão Espanholinhas                  1.0                0.0          0.0
          Francesinhas                   1.0                0.0          0.0
Obama     Bastardos Inglórios            0.0                0.0          0.0
          Brasileirinhas                 0.0                0.0          0.0
          Titanic                        0.0                1.0          0.0

                               Milf  Nacional  Oscar  Pornô  Romance  Surto  \
user      movie
Abelardo  Donnie Darko          0.0       0.0    0.0    0.0      0.0    1.0
          Life of Pi            0.0       0.0    1.0    0.0      0.0    1.0
          Titanic               0.0       0.0    0.0    0.0      1.0    0.0
Cris      Apocalypse now        0.0       0.0    0.0    0.0      0.0    0.0
          Chuck                 0.0       0.0    0.0    0.0      0.0    0.0
ElTaradão Espanholinhas         1.0       0.0    0.0    1.0      0.0    0.0
          Francesinhas          0.0       0.0    0.0    1.0      0.0    0.0
Obama     Bastardos Inglórios   0.0       0.0    0.0    0.0      0.0    0.0
          Brasileirinhas        1.0       1.0    0.0    1.0      0.0    0.0
          Titanic               0.0       0.0    0.0    0.0      1.0    0.0

                               Terror
user      movie
Abelardo  Donnie Darko            0.0
          Life of Pi              0.0
          Titanic                 0.0
Cris      Apocalypse now          0.0
          Chuck                   1.0
ElTaradão Espanholinhas           0.0
          Francesinhas            0.0
Obama     Bastardos Inglórios     0.0
          Brasileirinhas          0.0
          Titanic                 0.0

# Maxo, que nó doido